import { renderHeader, headerArgs } from "./Header.js";
import { figmaLinks } from "../../../.storybook/globals";

export default {
    title: "Layout/Header",
    render: renderHeader,
    args: { ...headerArgs },
    argTypes: {
        defaultBannerContainedBanner: {
            control: { type: "radio" },
            options: ["No", "Yes - light", "Yes - Dark"],
            mapping: {
                No: "No",
                "Yes - light": "qld__banner_contained",
                "Yes - Dark":
                    "qld__banner_contained qld__banner_contained--dark",
            },
            description: "Layout for displaying the contained banner if used.",
        },
        siteHeaderMainTheme: {
            control: { type: "radio" },
            options: ["Light", "Dark", "Dark Alternative"],
            mapping: {
                Light: "",
                Dark: "qld__header__main--dark",
                "Dark Alternative": "qld__header__main--dark-alt",
            },
            description: "Main header colour theme.",
        },
        sitePreHeaderTheme: {
            control: { type: "radio" },
            options: ["Light", "Dark", "Dark Alternative"],
            mapping: {
                Light: "",
                Dark: "qld__header__pre-header--dark",
                "Dark Alternative": "qld__header__pre-header--dark-alt",
            },
            description: "Pre header colour theme.",
        },
        siteShowLogo: {
            control: "radio",
            options: ["yes", "no"],
            description: "Show the Queensland Government logo",
        },
        containedBannerImageTexturePosition: {
            control: { type: "select" },
            options: ["Top Left", "Top Center", "Top Right"],
            mapping: {
                "Top Left": "top left",
                "Top Center": "top center",
                "Top Right": "top right",
            },
            description: "Position of the texture image within the banner.",
        },
        containedBannerImageTextureSize: {
            control: { type: "select" },
            options: ["Auto", "Cover"],
            mapping: {
                Auto: "auto",
                Cover: "cover",
            },
            description: "Size of the texture image within the banner.",
        },
        containedBannerImageTextureRepeat: {
            control: { type: "select" },
            options: ["No Repeat", "Repeat"],
            mapping: {
                "No Repeat": "no-repeat",
                Repeat: "repeat",
            },
            description: "Repeat style of the texture image within the banner.",
        },
        mainNavCtaOneIcon: {
            control: "select",
            options: [
                "arrow-up",
                "arrow-down",
                "arrow-left",
                "arrow-right",
                "view-all",
                "chevron-up",
                "chevron-down",
                "chevron-left",
                "chevron-right",
                "attach",
                "calendar",
                "close",
                "copy",
                "delete",
                "direction-up-down",
                "download",
                "edit",
                "enlarge",
                "favourite",
                "filter",
                "global-nav",
                "hide",
                "home",
                "language",
                "like",
                "location",
                "log-in",
                "log-out",
                "manage-accounts",
                "menu",
                "minus",
                "more-horizontal",
                "more-vertical",
                "pause",
                "play",
                "plus",
                "print",
                "refresh",
                "save",
                "search",
                "settings",
                "share",
                "show",
                "sort-alpha",
                "stop",
                "tick",
                "upload",
                "zoom",
                "alert-cancel",
                "alert-danger",
                "alert-error",
                "alert-information",
                "alert-maintenance",
                "alert-success",
                "alert-warning",
                "status-cancel",
                "status-danger",
                "status-error",
                "status-info",
                "status-maintenance",
                "status-success",
                "status-warning",
                "accessibility",
                "announcement",
                "article",
                "audio",
                "car",
                "chart",
                "clock",
                "code",
                "cost",
                "design",
                "directions",
                "document",
                "document-error",
                "document-pdf",
                "document-spreadsheet",
                "document-word",
                "external-link",
                "help",
                "identity",
                "identity-face",
                "image",
                "links",
                "lock",
                "lock-open",
                "Email",
                "microphone",
                "notifications",
                "notifications-circle",
                "op-ed",
                "parking",
                "pdf",
                "pending",
                "phone",
                "podcast",
                "profile",
                "speech",
                "spreadsheet",
                "transcript",
                "users",
                "video",
                "wheelchair",
                "Facebook",
                "Instagram",
                "LinkedIn",
                "X",
                "YouTube",
                "extended_facilty",
                "extended_child_health",
                "extended_blood",
                "extended_support_care",
                "extended_shield_with_heart",
                "extended_clinical_information",
                "extended_medical_staff",
                "extended_icon",
                "extended_surgical",
                "extended_masks",
                "extended_maternity",
                "extended_mental_health",
                "extended_dental",
                "extended_health_home",
                "extended_diagnosis",
                "extended_conditions",
                "extended_doctor",
                "extended_patient",
                "extended_biology",
                "extended_health_heart",
                "extended_ambulance",
                "extended_hospital",
                "extended_health_services",
                "extended_bone",
                "extended_coronavirus",
                "extended_patient_file",
                "extended_health_alert",
                "extended_vaccines",
                "extended_hospital_location",
                "extended_bed",
                "extended_current-location",
            ],
            description:
                "Icon class for the first call to action button in the main navigation (if used). E.g., 'icon-email'.",
        },
        mainNavCtaTwoIcon: {
            control: "select",
            options: [
                "arrow-up",
                "arrow-down",
                "arrow-left",
                "arrow-right",
                "view-all",
                "chevron-up",
                "chevron-down",
                "chevron-left",
                "chevron-right",
                "attach",
                "calendar",
                "close",
                "copy",
                "delete",
                "direction-up-down",
                "download",
                "edit",
                "enlarge",
                "favourite",
                "filter",
                "global-nav",
                "hide",
                "home",
                "language",
                "like",
                "location",
                "log-in",
                "log-out",
                "manage-accounts",
                "menu",
                "minus",
                "more-horizontal",
                "more-vertical",
                "pause",
                "play",
                "plus",
                "print",
                "refresh",
                "save",
                "search",
                "settings",
                "share",
                "show",
                "sort-alpha",
                "stop",
                "tick",
                "upload",
                "zoom",
                "alert-cancel",
                "alert-danger",
                "alert-error",
                "alert-information",
                "alert-maintenance",
                "alert-success",
                "alert-warning",
                "status-cancel",
                "status-danger",
                "status-error",
                "status-info",
                "status-maintenance",
                "status-success",
                "status-warning",
                "accessibility",
                "announcement",
                "article",
                "audio",
                "car",
                "chart",
                "clock",
                "code",
                "cost",
                "design",
                "directions",
                "document",
                "document-error",
                "document-pdf",
                "document-spreadsheet",
                "document-word",
                "external-link",
                "help",
                "identity",
                "identity-face",
                "image",
                "links",
                "lock",
                "lock-open",
                "Email",
                "microphone",
                "notifications",
                "notifications-circle",
                "op-ed",
                "parking",
                "pdf",
                "pending",
                "phone",
                "podcast",
                "profile",
                "speech",
                "spreadsheet",
                "transcript",
                "users",
                "video",
                "wheelchair",
                "Facebook",
                "Instagram",
                "LinkedIn",
                "X",
                "YouTube",
                "extended_facilty",
                "extended_child_health",
                "extended_blood",
                "extended_support_care",
                "extended_shield_with_heart",
                "extended_clinical_information",
                "extended_medical_staff",
                "extended_icon",
                "extended_surgical",
                "extended_masks",
                "extended_maternity",
                "extended_mental_health",
                "extended_dental",
                "extended_health_home",
                "extended_diagnosis",
                "extended_conditions",
                "extended_doctor",
                "extended_patient",
                "extended_biology",
                "extended_health_heart",
                "extended_ambulance",
                "extended_hospital",
                "extended_health_services",
                "extended_bone",
                "extended_coronavirus",
                "extended_patient_file",
                "extended_health_alert",
                "extended_vaccines",
                "extended_hospital_location",
                "extended_bed",
                "extended_current-location",
            ],
            description:
                "Icon class for the second call to action button in the main navigation (if used). E.g., 'icon-email'.",
        },
    },
    parameters: {
        layout: "fullscreen",
        design: {
            type: "figma",
            url: figmaLinks.header.design,
        },
    },
};

// Default story
export const Default = {
    args: {
        ...headerArgs,
        defaultBannerContainedBanner: "Yes - Dark",
    },
};

// Variants
export const LightHeader = (args) =>
    renderHeader({ ...args, siteHeaderMainTheme: "" });
LightHeader.args = { ...headerArgs };

export const DarkHeader = (args) =>
    renderHeader({ ...args, siteHeaderMainTheme: "qld__header__main--dark" });
DarkHeader.args = { ...headerArgs };

export const DarkAltHeader = (args) =>
    renderHeader({
        ...args,
        siteHeaderMainTheme: "qld__header__main--dark-alt",
    });
DarkAltHeader.args = { ...headerArgs };
