name: "Chromatic"

on:
  workflow_dispatch:
  push:
    branches: [master, 'release-**']
  pull_request:
    types: [opened, reopened, ready_for_review]
    branches: [master, 'release-**']
    paths-ignore:
      - '**/*.md'
      - 'docs/**'

concurrency:
  group: chromatic-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: 24.14.0
      - name: Install dependencies
        run: npm ci
      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          onlyChanged: true
          exitZeroOnChanges: true
